name: ci/cd

on:
  push:
    branches: [main]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Docker Push
        env:
          REPO: deploy-example
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest ${{secrets.DOCKER_USER}}/$REPO:latest
          docker push ${{secrets.DOCKER_USER}}/$REPO
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
